function onCreate()
     makeLuaSprite('screen', 'backgroundST', 0, 0)
     scaleObject('screen', 1, 1)
     setObjectCamera('screen', 'other')
     addLuaSprite('screen')

     makeLuaText('st_shadow', 'SOUND TEST', nil, 503, 203)
     setTextFont('st_shadow', 'sonic-cd-menu-font.ttf')
     setTextColor('st_shadow', '000000')
     setTextBorder('st_shadow', 0)
     setTextSize('st_shadow', 30)
     setObjectCamera('st_shadow', 'other')
     addLuaText('st_shadow')

     makeLuaText('st', 'SOUND TEST', nil, 500, 200)
     setTextFont('st', 'sonic-cd-menu-font.ttf')
     setTextColor('st', '0fabf3')
     setTextBorder('st', 0)
     setTextSize('st', 30)
     setObjectCamera('st', 'other')
     addLuaText('st', true)

     makeLuaText('pcm_shadow', 'PCM  NO . ', nil, 253, 403)
     setTextFont('pcm_shadow', 'sonic-cd-menu-font.ttf')
     setTextColor('pcm_shadow', '6b6c91')
     setTextBorder('pcm_shadow', 0)
     setTextSize('pcm_shadow', 30)
     setObjectCamera('pcm_shadow', 'other')
     addLuaText('pcm_shadow', true)

     makeLuaText('pcm', 'PCM  NO . ', nil, 250, 400)
     setTextFont('pcm', 'sonic-cd-menu-font.ttf')
     setTextColor('pcm', 'b1adf7')
     setTextBorder('pcm', 0)
     setTextSize('pcm', 30)
     setObjectCamera('pcm', 'other')
     addLuaText('pcm', true)

     makeLuaText('da_shadow', 'DA  NO . ', nil, 753, 403)
     setTextFont('da_shadow', 'sonic-cd-menu-font.ttf')
     setTextColor('da_shadow', '6b6c91')
     setTextBorder('da_shadow', 0)
     setTextSize('da_shadow', 30)
     setObjectCamera('da_shadow', 'other')
     addLuaText('da_shadow', true)

     makeLuaText('da', 'DA  NO . ', nil, 750, 400)
     setTextFont('da', 'sonic-cd-menu-font.ttf')
     setTextColor('da', 'b1adf7')
     setTextBorder('da', 0)
     setTextSize('da', 30)
     setObjectCamera('da', 'other')
     addLuaText('da', true)

     close(true)
end